const categories = [
    { value: "MP", label: "Minutes Per Game (MPG)" },
    { value: "PTS", label: "Points Per Game (PPG)" },
    { value: "TRB", label: "Rebounds Per Game (RPG)" },
    { value: "AST", label: "Assists Per Game (APG)" },
    { value: "STL", label: "Steals Per Game (SPG)" },
    { value: "BLK", label: "Blocks Per Game (BPG)" },
    { value: "FG", label: "Field Goals Made (FGM)" },
    { value: "FGA", label: "Field Goals Attempted (FGA)" },
    { value: "FGPercent", label: "Field Goal Percentage (FG%)" },
    { value: "threeP", label: "Three-Point Field Goals Made (3PM)" },
    { value: "threePA", label: "Three-Point Field Goals Attempted (3PA)" },
    { value: "threePPercent", label: "Three-Point Field Goal Percentage (3P%)" },
    { value: "twoP", label: "Two-Point Field Goals Made (2PM)" },
    { value: "twoPA", label: "Two-Point Field Goals Attempted (2PA)" },
    { value: "twoPPercent", label: "Two-Point Field Goal Percentage (2P%)" },
    { value: "eFGPercent", label: "Effective Field Goal Percentage (eFG%)" },
    { value: "FT", label: "Free Throws Made (FTM)" },
    { value: "FTA", label: "Free Throws Attempted (FTA)" },
    { value: "FTPercent", label: "Free Throw Percentage (FT%)" },
    { value: "ORB", label: "Offensive Rebounds (ORB)" },
    { value: "DRB", label: "Defensive Rebounds (DRB)" },
    { value: "TOV", label: "Turnovers (TOV)" },
    { value: "PF", label: "Personal Fouls (PF)" },
];

export default categories;
